Repository AY2021S1-CS2103T-T09-1/tp, pull requests merged in 2020-11, with the labels that each got.

#145 Change log from addressbook to gradpad
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: priority.Low, severity.Low, type.Task

#168 Fix checkmc command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CheckMcCommand.java
  src/test/java/seedu/address/logic/commands/CheckMcCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, type.Bug

#173 Create first draft of PPP (sam)
  docs/team/silvernitro.md
Labels: documentation, type.Task

#169 Expanded yes command and fixed case-sensitive issues
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
Labels: priority.Medium, severity.Medium, type.Bug

#172 Update ug v1.4
  docs/UserGuide.md
Labels: documentation, priority.Medium, severity.Low

#177 First PPP draft (yan)
  docs/team/yan-soon.md
Labels: documentation, priority.Medium, type.Task

#170 Case insensitive tags within each module
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/GradPad.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium, type.Enhancement

#171 Enhancement/multiword tags
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/model/module/ModuleContainsTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: priority.Medium, type.Enhancement

#175 Add check for equal fields in edit command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, severity.Medium, type.Bug

#174 Add semesterdata
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/nusmods/ModuleInfo.java
  src/main/resources/data/modules.json
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/resources/NusmodsDataManagerTest/CS1010X.json
  src/test/resources/NusmodsDataManagerTest/IS1103.json
  src/test/resources/NusmodsDataManagerTest/validModule.json
  src/test/resources/NusmodsDataManagerTest/validModuleMap.json
Labels: priority.Medium, severity.Medium, type.Enhancement, type.Task

#179 Branch ppp
  docs/team/shaokiat.md
Labels: documentation, type.Task

#178 Add fdelete fclear command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ForceClearCommand.java
  src/main/java/seedu/address/logic/commands/ForceDeleteCommand.java
  src/main/java/seedu/address/logic/parser/ForceDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/test/java/seedu/address/logic/commands/ForceClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ForceDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ForceDeleteCommandParserTest.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Enhancement

#176 Update required command
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/commands/GemCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/storage/GemCommandStorage.java
  src/main/java/seedu/address/storage/RequiredCommandMessages.java
  src/main/java/seedu/address/storage/RequiredCommandStorage.java
  src/main/resources/data/precludedmodules.json
  src/test/data/RequiredCommandTest/incompletefoundationmodules.json
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
  src/test/java/seedu/address/storage/RequiredCommandStorageTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#192 DG: Add Tags feature
  docs/DeveloperGuide.md
  docs/diagrams/AddModuleTagsSequenceDiagram.puml
  docs/diagrams/DeleteModuleTagsSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddModuleTagsSequenceDiagram.png
  docs/images/DeleteModuleTagsSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#180 (v1.4 DG Update) Add required, gem and science command, Storage component and v1.4 manual testing
  docs/DeveloperGuide.md
  docs/diagrams/GemSequenceDiagram.puml
  docs/diagrams/RequiredSequenceDiagram.puml
  docs/diagrams/ScienceSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/GemSequenceDiagram.png
  docs/images/RequiredSequenceDiagram.png
  docs/images/ScienceSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#182 Update gem & science commands to support auto update
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/GemCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/storage/GemCommandPaths.java
  src/main/java/seedu/address/storage/GemCommandStorage.java
  src/main/resources/data/GEM/GEHsem1.json
  src/test/data/GemCommandTest/compiledsem1GEmodules.json
  src/test/data/GemCommandTest/compiledsem2GEmodules.json
  src/test/java/seedu/address/logic/commands/GemCommandTest.java
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
  src/test/java/seedu/address/logic/commands/ScienceCommandTest.java
  src/test/java/seedu/address/storage/GemCommandStorageTest.java
Labels: priority.Medium, severity.Low, type.Bug, type.Enhancement

#194 Update DG Search, Delete, manual testing
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/SearchSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#196 Update search feature implementation & improve test coverage
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/ModuleInfoSearcher.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/logic/ModuleInfoSearcherTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/nusmods/NusmodsDataManagerTest.java
Labels: priority.Medium, severity.Medium, type.Enhancement

#197 Improve test coverage
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/GemCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/storage/GemCommandStorage.java
  src/main/java/seedu/address/storage/RequiredCommandStorage.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/YesCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
Labels: priority.Medium, type.Enhancement, type.Task

#198 DG: Nusmods implementation
  docs/DeveloperGuide.md
  docs/diagrams/NusmodsFetchLocalModuleSequenceDiagram.puml
  docs/diagrams/NusmodsFetchModuleSequenceDiagram.puml
  docs/diagrams/NusmodsScrapeModuleSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/NusmodsFetchLocalModuleSequenceDiagram.png
  docs/images/NusmodsFetchModuleSequenceDiagram.png
  docs/images/NusmodsScrapeModuleSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#200 Increase test coverage
  src/main/java/seedu/address/commons/exceptions/IllegalValueException.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/model/module/ModularCreditsTest.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/ModuleTitleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
Labels: priority.Low, type.Enhancement, type.Task

#203 PPP draft (Syafiq)
  docs/team/mhdsyfq.md
Labels: documentation, type.Task

#204 Improve test coverage
  src/test/data/SampleDataUtilTest/samplemodules.json
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/GradPadTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/tag/UniqueTagMapTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Low, type.Task

#202 add tip for required command
  docs/UserGuide.md
Labels: documentation, priority.Low, type.Task

#209 UG: case insensitive tags + images
  docs/UserGuide.md
  docs/images/Gem2.png
  docs/images/Science2.png
  docs/images/Search2.png
Labels: documentation, priority.High, type.Task

#208 Add tests for parsers
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/ModuleInfoSearcherTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, type.Task

#210 Update DG: Add appendix for effort
  docs/DeveloperGuide.md
  docs/images/nusmods_small.png
Labels: documentation, priority.Medium, type.Task

#212 Update readme and index page
  README.md
  docs/UserGuide.md
  docs/images/AnnotatedUi.png
  docs/images/Ui.png
  docs/index.md
Labels: documentation, priority.High, type.Task

#216 UG: address vetting comments
  docs/UserGuide.md
  docs/images/Clear1.png
  docs/images/Clear2.png
  docs/images/Clear3.png
Labels: documentation, priority.High, type.Task

#214 Include NUSMods integration for add and edit
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#215 Update find feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#217 Add stalled feature and updated delete feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/CancelStalledSequenceDiagram.puml
  docs/diagrams/ConfirmStalledSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StalledActivityDiagram.puml
  docs/diagrams/StalledSequenceDiagram.puml
  docs/images/CancelStalledSequenceDiagram.png
  docs/images/ConfirmStalledSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/StalledActivityDiagram.png
  docs/images/StalledSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#218 Update UG and DG as per vetting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GemSequenceDiagram.puml
  docs/diagrams/RequiredSequenceDiagram.puml
  docs/diagrams/ScienceSequenceDiagram.puml
  docs/images/GemSequenceDiagram.png
  docs/images/RequiredSequenceDiagram.png
  docs/images/ScienceSequenceDiagram.png
Labels: documentation, priority.Medium, type.Task

#219 Refactor Index
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Low, type.Task

#226 Update javadocs
  docs/team/johndoe.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/ModuleInfoSearcher.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ForceClearCommand.java
  src/main/java/seedu/address/logic/commands/ForceDeleteCommand.java
  src/main/java/seedu/address/logic/commands/GemCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/YesCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ForceDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: documentation, priority.Low

#223 update javadocs and remove unused variables
  src/main/java/seedu/address/storage/GradPadStorage.java
  src/main/java/seedu/address/storage/JsonGradPadStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/test/java/seedu/address/storage/GemCommandStorageTest.java
  src/test/java/seedu/address/storage/RequiredCommandStorageTest.java
Labels: priority.Medium, type.Task
