Repository AY2021S1-CS2103T-T09-1/tp, pull requests merged in 2020-10, with the labels that each got.

#42 Update DG Storage component and add Edit implementation
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#51 Improve GUI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High, type.Task

#52 Update Ui layout and descriptions of GradPad
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, priority.Medium, type.Task

#45 update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#57 Implement checkmc command
  src/main/java/seedu/address/logic/commands/CheckMcCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/test/java/seedu/address/logic/commands/CheckMcCommandTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task

#58 Add feature to use NUSMods data
  modules.json
  src/main/java/seedu/address/commons/util/HttpUtil.java
  src/main/java/seedu/address/nusmods/DataFetcher.java
  src/main/java/seedu/address/nusmods/DataFetcherManager.java
  src/main/java/seedu/address/nusmods/ModuleInfo.java
  src/main/java/seedu/address/nusmods/ModuleSummary.java
  src/main/java/seedu/address/nusmods/NusmodsData.java
  src/main/java/seedu/address/nusmods/NusmodsDataManager.java
  src/main/java/seedu/address/nusmods/exceptions/NusmodsException.java
  src/test/data/NusmodsDataManagerTest/CS1010X.json
  src/test/data/NusmodsDataManagerTest/CS1010XSummary.json
  src/test/data/NusmodsDataManagerTest/IS1103.json
  src/test/data/NusmodsDataManagerTest/IS1103Summary.json
  src/test/data/NusmodsDataManagerTest/invalidModule.json
  src/test/data/NusmodsDataManagerTest/invalidModuleMap.json
  src/test/data/NusmodsDataManagerTest/validModule.json
  src/test/data/NusmodsDataManagerTest/validModuleMap.json
  src/test/data/NusmodsDataManagerTest/validSummaries.json
  src/test/java/seedu/address/commons/util/HttpUtilTest.java
  src/test/java/seedu/address/nusmods/DataFetcherManagerTest.java
  src/test/java/seedu/address/nusmods/ModuleInfoTest.java
  src/test/java/seedu/address/nusmods/ModuleSummaryTest.java
  src/test/java/seedu/address/nusmods/NusmodsDataManagerTest.java
Labels: priority.High

#55 Update DG model and delete feature
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#62 Update DG and UG - UI component and Find feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#66 Change GUI colors, icon and minor adjustments
  src/main/resources/images/gradpad.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium, type.Task

#64 Add Edit command to UG
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#74 Refactor helpwindow and command result + minor nits
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/CheckMcCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/CheckMcCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.Medium, type.Task

#70 Update feature descriptions and images for UG, Add Intro for DG and update HelpCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/add.png
  docs/images/checkmc.png
  docs/images/edit.png
  docs/images/find.png
  docs/images/help.png
  docs/images/list.png
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: documentation, priority.Medium, type.Task

#80 Bugfix: make NusmodsDataManager constructor public
  src/main/java/seedu/address/nusmods/NusmodsDataManager.java
Labels: priority.High, severity.High, type.Bug

#78 DG: Add v1.3 commands and NUSMODS component
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CheckMcSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/ModelFilteredListClassDiagram.puml
  docs/diagrams/NusmodsClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/CheckMcSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/ModelFilteredListClassDiagram.png
  docs/images/NusmodsClassDiagram.png
Labels: documentation, priority.Medium, type.Task

#84 Add assertions to Nusmods package
  build.gradle
  src/main/java/seedu/address/nusmods/DataFetcherManager.java
  src/main/java/seedu/address/nusmods/NusmodsDataManager.java
Labels: priority.Low, type.Task

#77 Change find command to allow better searches
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleCodeContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: priority.Medium, type.Task

#87 Update dg: manual testing
  docs/DeveloperGuide.md
Labels: documentation, priority.Low, type.Task

#89 UG: Update Ui and Delete command images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/delete.png
Labels: documentation, priority.Medium, type.Task

#83 UG: Explain auto name-tagging when adding modules
  docs/UserGuide.md
Labels: documentation, priority.Low, type.Task

#92 Add assertions
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/module/ModuleCodeContainsKeywordsPredicate.java
Labels: priority.Low, type.Task

#99 add assertions for GradPad.java and ModelManager.java
  src/main/java/seedu/address/model/GradPad.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Low, type.Task

#75 Update User Guide, Developer Guide v1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation, hacktoberfest-accepted, priority.Medium, type.Task

#95 Implement delay on Exit
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: priority.Low, type.Task

#94 Implement confirmation for Clear and Delete commands
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/YesCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
Labels: priority.Medium, type.Task

#97 Required and Science command
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/storage/RequiredCommandMessages.java
  src/main/java/seedu/address/storage/RequiredCommandStorage.java
  src/main/resources/data/ITProfessionalism.json
  src/main/resources/data/foundationmodules.json
  src/main/resources/data/industrialexperience.json
  src/main/resources/data/mathandsciencemodules.json
  src/main/resources/data/sciencemodules.json
  src/test/data/RequiredCommandTest/compiledmodules.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
  src/test/java/seedu/address/logic/commands/ScienceCommandTest.java
  src/test/java/seedu/address/storage/RequiredCommandStorageTest.java
Labels: hacktoberfest-accepted, priority.Medium, type.Task

#100 Search feature implementation
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/ModuleInfoSearcher.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/ModuleInfoSearcherTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: hacktoberfest-accepted, priority.Medium, type.Task

#105 Add assertion for StorageManager class
  src/main/java/seedu/address/storage/StorageManager.java
Labels: priority.Low, type.Task

#102 Add mark-up images for Commands section and rephrased command descriptions
  docs/UserGuide.md
  docs/images/Add1.png
  docs/images/Add2.png
  docs/images/CheckMc1.png
  docs/images/CheckMc2.png
  docs/images/Delete1.png
  docs/images/Delete2.png
  docs/images/Delete3.png
  docs/images/Delete4.png
  docs/images/Edit1.png
  docs/images/Edit2.png
  docs/images/Exit1.png
  docs/images/Exit2.png
  docs/images/Find1.png
  docs/images/Find2.png
  docs/images/Help1.png
  docs/images/Help2.png
  docs/images/List1.png
  docs/images/List2.png
  docs/images/Ui.png
Labels: documentation, priority.Medium, type.Task

#106 add more tests to improve RequiredCommandTest test coverage
  src/test/data/RequiredCommandTest/doublemodules.json
  src/test/data/RequiredCommandTest/incompletefoundationmodules.json
  src/test/data/RequiredCommandTest/singlemodule.json
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
Labels: priority.Low, type.Task

#113 Address UG peer review feedback
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#108 Add required modules to NUSMods + fix resource dependencies
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/nusmods/DataFetcher.java
  src/main/java/seedu/address/nusmods/DataFetcherManager.java
  src/main/java/seedu/address/nusmods/NusmodsDataManager.java
  src/main/java/seedu/address/nusmods/NusmodsKeywords.java
  src/main/resources/data/modules.json
  src/test/java/seedu/address/logic/ModuleInfoSearcherTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/nusmods/DataFetcherManagerTest.java
  src/test/java/seedu/address/nusmods/ModuleInfoTest.java
  src/test/java/seedu/address/nusmods/ModuleSummaryTest.java
  src/test/java/seedu/address/nusmods/NusmodsDataManagerTest.java
  src/test/resources/NusmodsDataManagerTest/CS1010X.json
  src/test/resources/NusmodsDataManagerTest/CS1010XSummary.json
  src/test/resources/NusmodsDataManagerTest/IS1103.json
  src/test/resources/NusmodsDataManagerTest/IS1103Summary.json
  src/test/resources/NusmodsDataManagerTest/invalidModule.json
  src/test/resources/NusmodsDataManagerTest/invalidModuleMap.json
  src/test/resources/NusmodsDataManagerTest/validModule.json
  src/test/resources/NusmodsDataManagerTest/validModuleMap.json
  src/test/resources/NusmodsDataManagerTest/validSummaries.json
Labels: priority.Medium, severity.High, type.Bug

#117 Add required, science and search commands and edit minor details of the UG
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#115 Fix bugs for Required and Science command not being able to load JSON files.
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/storage/RequiredCommandMessages.java
  src/main/java/seedu/address/storage/RequiredCommandStorage.java
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
  src/test/java/seedu/address/logic/commands/ScienceCommandTest.java
  src/test/java/seedu/address/storage/RequiredCommandStorageTest.java
Labels: priority.Medium, severity.High, type.Bug

#111 Change implementation and format for add and edit command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleTitle.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/data/ITProfessionalism.json
  src/main/resources/data/foundationmodules.json
  src/main/resources/data/industrialexperience.json
  src/main/resources/data/mathandsciencemodules.json
  src/main/resources/data/sciencemodules.json
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ModuleListCard.fxml
  src/test/data/JsonSerializableGradPadTest/duplicateModuleGradPad.json
  src/test/data/JsonSerializableGradPadTest/typicalModulesGradPad.json
  src/test/data/RequiredCommandTest/compiledmodules.json
  src/test/data/RequiredCommandTest/doublemodules.json
  src/test/data/RequiredCommandTest/incompletefoundationmodules.json
  src/test/data/RequiredCommandTest/singlemodule.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/ModuleTitleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/EditModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/TypicalModuleCodes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.Medium, type.Task

#120 Update delete feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
Labels: priority.Medium, type.Task

#128 Update search command to include modular credits
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
Labels: priority.Medium, type.Task

#122 Add Tags command and support finding by tags
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/model/GradPad.java
  src/main/java/seedu/address/model/ReadOnlyGradPad.java
  src/main/java/seedu/address/model/module/CompoundFindPredicate.java
  src/main/java/seedu/address/model/module/ModuleContainsTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagMap.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/TagsCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
  src/test/java/seedu/address/model/GradPadTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagMapTest.java
Labels: priority.Medium, type.Story

#127 Include intro display for GUI
  src/main/java/seedu/address/ui/IntroDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/images/logo.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/IntroDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.Medium, type.Task

#131 UG: Add tags command + update add, edit, find commands
  docs/UserGuide.md
Labels: documentation, priority.High, type.Task

#134 Update ug/v1.3
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.Task

#133 Required command addons
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/commands/GemCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModularCredits.java
  src/main/java/seedu/address/model/module/ModuleTitle.java
  src/main/java/seedu/address/storage/GemCommandPaths.java
  src/main/java/seedu/address/storage/GemCommandStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonSerializableGradPad.java
  src/main/java/seedu/address/storage/RequiredCommandMessages.java
  src/main/java/seedu/address/storage/RequiredCommandStorage.java
  src/main/resources/data/GEM/GEHs1.json
  src/main/resources/data/GEM/GEHsem2.json
  src/main/resources/data/GEM/GEQ.json
  src/main/resources/data/GEM/GER.json
  src/main/resources/data/GEM/GESsem1.json
  src/main/resources/data/GEM/GESsem2.json
  src/main/resources/data/GEM/GETsem1.json
  src/main/resources/data/GEM/GETsem2.json
  src/main/resources/data/mathmodules.json
  src/test/data/GemCommandTest/compiledsem1GEmodules.json
  src/test/data/GemCommandTest/compiledsem2GEmodules.json
  src/test/data/RequiredCommandTest/compiledmodules.json
  src/test/java/seedu/address/logic/commands/GemCommandTest.java
  src/test/java/seedu/address/logic/commands/RequiredCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/module/ModularCreditsTest.java
  src/test/java/seedu/address/model/module/ModuleTitleTest.java
  src/test/java/seedu/address/storage/GemCommandStorageTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/RequiredCommandStorageTest.java
Labels: priority.Medium, type.Task

#130 Update UG with comments by Serene and Hanming
  docs/UserGuide.md
  docs/images/nusmods.png
Labels: documentation, priority.Low, type.Task

#139 Clean up messages
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CheckMcCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RequiredCommand.java
  src/main/java/seedu/address/logic/commands/ScienceCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/TagsCommand.java
  src/main/java/seedu/address/logic/commands/YesCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/GradPadParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/GradPad.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/ModularCredits.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleTitle.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckMcCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ScienceCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/commands/TagsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradPadParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.Medium, type.Task

#143 Add/replace images & minor nits
  docs/UserGuide.md
  docs/images/Add1.png
  docs/images/Add2.png
  docs/images/CheckMc1.png
  docs/images/CheckMc2.png
  docs/images/Delete1.png
  docs/images/Delete2.png
  docs/images/Delete3.png
  docs/images/Delete4.png
  docs/images/Edit1.png
  docs/images/Edit2.png
  docs/images/Exit1.png
  docs/images/Exit2.png
  docs/images/Find1.png
  docs/images/Find2.png
  docs/images/Gem1.png
  docs/images/Gem2.png
  docs/images/Help1.png
  docs/images/Help2.png
  docs/images/List1.png
  docs/images/List2.png
  docs/images/Required1.png
  docs/images/Required2.png
  docs/images/Science1.png
  docs/images/Science2.png
  docs/images/Search1.png
  docs/images/Search2.png
  docs/images/Tags1.png
  docs/images/Tags2.png
  docs/images/Ui.png
Labels: documentation, priority.Medium, type.Task
